using Data.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Business.Dtos;

public class ProjectRegistrationForm
{
    public int ProjectId { get; set; }

    public string ProjectName { get; set; } = null!;

    public DateTime StartDate { get; set; } /* Make DateTime? */

    public DateTime EndDate { get; set; } /* Make DateTime? */

    public string ProjectManager { get; set; } = null!;

    public int CustomerId { get; set; } /* Generated by chatgpt 4o, using CustomerId and not name as reference to Customers */

    public decimal TotalCost { get; set; } /*, chatgpt4o generated/suggested decimal instead of int */

    public int StatusId { get; set; }
}
