using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Business.Dtos;

public class ProjectUpdateForm()
{
    public string ProjectName { get; set; } = null!;

    public string StartDate { get; set; } = null!; /* Make DateTime? */

    public string EndDate { get; set; } = null!; /* Make DateTime? */

    public string ProjectManager { get; set; } = null!;

    public int CustomerId { get; set; } /* Generated by chatgpt 4o, using CustomerId and not name as reference to Customers */

    public decimal TotalCost { get; set; } /*, chatgpt4o generated/suggested decimal instead of int */

    public string Status { get; set; } = null!;
}
