using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Data.Entities;

public class ProjectEntity
{
    [Key]
    public int ProjectId { get; set; }
    
    [Required]
    [Column(TypeName = "nvarchar(50)")]
    public string ProjectName { get; set; } = null!;
    
    [Required]
    [Column(TypeName = "nvarchar(50)")]
    public string StartDate { get; set; } = null!; /* Make DateTime? */
    
    [Required]
    [Column(TypeName = "nvarchar(50)")]
    public string EndDate { get; set; } = null!; /* Make DateTime? */

    [Required]
    [Column(TypeName = "nvarchar(50)")]
    public string ProjectManager { get; set; } = null!;
    
    [Required]
    [Column(TypeName = "nvarchar(50)")]
    [ForeignKey("CustomerEntity")] /* Generated by chatgpt 4o, using the foreign key to link to customer */
    public string Name { get; set; } = null!;
    
    [Required]
    public decimal TotalCost { get; set; } /*, chatgpt4o generated/suggested decimal instead of int */

    [Required]
    [Column(TypeName = "nvarchar(50)")]
    public string Status { get; set; } = null!;

    /* Generated by chatgpt 4o, navigation for the property customer */
    public CustomerEntity Customer { get; set; } = null!;
}
